package swing;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    double firstnum, secondnum, result;
    String operations;
    private Object math;

    public Calculator() {
        initComponents();

        jRadioButton1.setEnabled(false);
    }

    @Override
    public void disable() {
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);

        jTextField1.setEnabled(false);
        plusButton1.setEnabled(false);
        plusButton2.setEnabled(false);
        plusButton3.setEnabled(false);
        plusButton4.setEnabled(false);
        plusButton7.setEnabled(false);
        plusButton8.setEnabled(false);
        plusButton9.setEnabled(false);
        plusButton10.setEnabled(false);
        plusButton11.setEnabled(false);
        plusButton12.setEnabled(false);
        plusButton13.setEnabled(false);
        plusButton14.setEnabled(false);
        plusButton15.setEnabled(false);
        plusButton16.setEnabled(false);
        plusButton17.setEnabled(false);
        plusButton18.setEnabled(false);
        plusButton19.setEnabled(false);
        plusButton20.setEnabled(false);
        plusButton21.setEnabled(false);
        plusButton22.setEnabled(false);
        plusButton23.setEnabled(false);
        plusButton25.setEnabled(false);
        plusButton26.setEnabled(false);
        plusButton27.setEnabled(false);
        plusButton28.setEnabled(false);
        plusButton30.setEnabled(false);
        plusButton30.setEnabled(false);
        plusButton31.setEnabled(false);
        plusButton32.setEnabled(false);
        plusButton34.setEnabled(false);
        plusButton37.setEnabled(false);
        plusButton38.setEnabled(false);
        plusButton39.setEnabled(false);
        plusButton40.setEnabled(false);
        plusButton41.setEnabled(false);
        plusButton42.setEnabled(false);
        plusButton43.setEnabled(false);
        plusButton44.setEnabled(false);
    }

    @Override
    public void enable() {
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);

        jTextField1.setEnabled(true);
        plusButton1.setEnabled(true);
        plusButton2.setEnabled(true);
        plusButton3.setEnabled(true);
        plusButton4.setEnabled(true);
        plusButton7.setEnabled(true);
        plusButton8.setEnabled(true);
        plusButton9.setEnabled(true);
        plusButton10.setEnabled(true);
        plusButton11.setEnabled(true);
        plusButton12.setEnabled(true);
        plusButton13.setEnabled(true);
        plusButton14.setEnabled(true);
        plusButton15.setEnabled(true);
        plusButton16.setEnabled(true);
        plusButton17.setEnabled(true);
        plusButton18.setEnabled(true);
        plusButton19.setEnabled(true);
        plusButton20.setEnabled(true);
        plusButton21.setEnabled(true);
        plusButton22.setEnabled(true);
        plusButton23.setEnabled(true);
        plusButton25.setEnabled(true);
        plusButton26.setEnabled(true);
        plusButton27.setEnabled(true);
        plusButton28.setEnabled(true);
        plusButton30.setEnabled(true);
        plusButton30.setEnabled(true);
        plusButton31.setEnabled(true);
        plusButton32.setEnabled(true);
        plusButton34.setEnabled(true);
        plusButton37.setEnabled(true);
        plusButton38.setEnabled(true);
        plusButton39.setEnabled(true);
        plusButton40.setEnabled(true);
        plusButton41.setEnabled(true);
        plusButton42.setEnabled(true);
        plusButton43.setEnabled(true);
        plusButton44.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        plusButton9 = new javax.swing.JButton();
        plusButton38 = new javax.swing.JButton();
        plusButton10 = new javax.swing.JButton();
        plusButton39 = new javax.swing.JButton();
        plusButton11 = new javax.swing.JButton();
        plusButton12 = new javax.swing.JButton();
        plusButton40 = new javax.swing.JButton();
        plusButton41 = new javax.swing.JButton();
        plusButton13 = new javax.swing.JButton();
        plusButton42 = new javax.swing.JButton();
        plusButton14 = new javax.swing.JButton();
        plusButton43 = new javax.swing.JButton();
        plusButton15 = new javax.swing.JButton();
        plusButton44 = new javax.swing.JButton();
        plusButton16 = new javax.swing.JButton();
        plusButton26 = new javax.swing.JButton();
        plusButton17 = new javax.swing.JButton();
        plusButton27 = new javax.swing.JButton();
        plusButton18 = new javax.swing.JButton();
        plusButton30 = new javax.swing.JButton();
        plusButton19 = new javax.swing.JButton();
        plusButton32 = new javax.swing.JButton();
        plusButton20 = new javax.swing.JButton();
        plusButton22 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        plusButton21 = new javax.swing.JButton();
        plusButton23 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        plusButton4 = new javax.swing.JButton();
        plusButton1 = new javax.swing.JButton();
        plusButton25 = new javax.swing.JButton();
        plusButton2 = new javax.swing.JButton();
        plusButton28 = new javax.swing.JButton();
        plusButton3 = new javax.swing.JButton();
        plusButton31 = new javax.swing.JButton();
        plusButton7 = new javax.swing.JButton();
        plusButton34 = new javax.swing.JButton();
        plusButton8 = new javax.swing.JButton();
        plusButton37 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 200));
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 450));

        plusButton9.setBackground(new java.awt.Color(204, 204, 204));
        plusButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton9.setText("5");
        plusButton9.setToolTipText("Add");
        plusButton9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton9ActionPerformed(evt);
            }
        });

        plusButton38.setBackground(new java.awt.Color(204, 204, 204));
        plusButton38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton38.setText("cos");
        plusButton38.setToolTipText("Add");
        plusButton38.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton38.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton38ActionPerformed(evt);
            }
        });

        plusButton10.setBackground(new java.awt.Color(204, 204, 204));
        plusButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton10.setText("6");
        plusButton10.setToolTipText("Add");
        plusButton10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton10ActionPerformed(evt);
            }
        });

        plusButton39.setBackground(new java.awt.Color(204, 204, 204));
        plusButton39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton39.setText("tan");
        plusButton39.setToolTipText("Add");
        plusButton39.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton39.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton39ActionPerformed(evt);
            }
        });

        plusButton11.setBackground(new java.awt.Color(204, 204, 204));
        plusButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton11.setText("*");
        plusButton11.setToolTipText("Add");
        plusButton11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton11ActionPerformed(evt);
            }
        });

        plusButton12.setBackground(new java.awt.Color(204, 204, 204));
        plusButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton12.setText("7");
        plusButton12.setToolTipText("Add");
        plusButton12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton12ActionPerformed(evt);
            }
        });

        plusButton40.setBackground(new java.awt.Color(204, 204, 204));
        plusButton40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton40.setText("ln");
        plusButton40.setToolTipText("Add");
        plusButton40.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton40.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton40ActionPerformed(evt);
            }
        });

        plusButton41.setBackground(new java.awt.Color(204, 204, 204));
        plusButton41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton41.setText("sinh");
        plusButton41.setToolTipText("Add");
        plusButton41.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton41.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton41ActionPerformed(evt);
            }
        });

        plusButton13.setBackground(new java.awt.Color(204, 204, 204));
        plusButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton13.setText("8");
        plusButton13.setToolTipText("Add");
        plusButton13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton13ActionPerformed(evt);
            }
        });

        plusButton42.setBackground(new java.awt.Color(204, 204, 204));
        plusButton42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton42.setText("cosh");
        plusButton42.setToolTipText("Add");
        plusButton42.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton42.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton42ActionPerformed(evt);
            }
        });

        plusButton14.setBackground(new java.awt.Color(204, 204, 204));
        plusButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton14.setText("9");
        plusButton14.setToolTipText("Add");
        plusButton14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton14ActionPerformed(evt);
            }
        });

        plusButton43.setBackground(new java.awt.Color(204, 204, 204));
        plusButton43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton43.setText("tanh");
        plusButton43.setToolTipText("Add");
        plusButton43.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton43.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton43ActionPerformed(evt);
            }
        });

        plusButton15.setBackground(new java.awt.Color(204, 204, 204));
        plusButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton15.setText("/");
        plusButton15.setToolTipText("Add");
        plusButton15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton15ActionPerformed(evt);
            }
        });

        plusButton44.setBackground(new java.awt.Color(204, 204, 204));
        plusButton44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton44.setText("e");
        plusButton44.setToolTipText("Add");
        plusButton44.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton44.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton44ActionPerformed(evt);
            }
        });

        plusButton16.setBackground(new java.awt.Color(204, 204, 204));
        plusButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton16.setText("2");
        plusButton16.setToolTipText("Add");
        plusButton16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton16ActionPerformed(evt);
            }
        });

        plusButton26.setBackground(new java.awt.Color(204, 204, 204));
        plusButton26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton26.setText("%");
        plusButton26.setToolTipText("Add");
        plusButton26.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton26ActionPerformed(evt);
            }
        });

        plusButton17.setBackground(new java.awt.Color(204, 204, 204));
        plusButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton17.setText("3");
        plusButton17.setToolTipText("Add");
        plusButton17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton17ActionPerformed(evt);
            }
        });

        plusButton27.setBackground(new java.awt.Color(204, 204, 204));
        plusButton27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton27.setText("Hex");
        plusButton27.setToolTipText("Add");
        plusButton27.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton27.setPreferredSize(new java.awt.Dimension(80, 30));
        plusButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton27ActionPerformed(evt);
            }
        });

        plusButton18.setBackground(new java.awt.Color(204, 204, 204));
        plusButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton18.setText("1");
        plusButton18.setToolTipText("Add");
        plusButton18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton18ActionPerformed(evt);
            }
        });

        plusButton30.setBackground(new java.awt.Color(204, 204, 204));
        plusButton30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton30.setText("Bin");
        plusButton30.setToolTipText("Add");
        plusButton30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton30.setPreferredSize(new java.awt.Dimension(80, 30));
        plusButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton30ActionPerformed(evt);
            }
        });

        plusButton19.setBackground(new java.awt.Color(204, 204, 204));
        plusButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton19.setText("=");
        plusButton19.setToolTipText("Add");
        plusButton19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton19ActionPerformed(evt);
            }
        });

        plusButton32.setBackground(new java.awt.Color(204, 204, 204));
        plusButton32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton32.setText("Oct");
        plusButton32.setToolTipText("Add");
        plusButton32.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton32.setPreferredSize(new java.awt.Dimension(80, 30));
        plusButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton32ActionPerformed(evt);
            }
        });

        plusButton20.setBackground(new java.awt.Color(204, 204, 204));
        plusButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton20.setText(".");
        plusButton20.setToolTipText("Add");
        plusButton20.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton20ActionPerformed(evt);
            }
        });

        plusButton22.setBackground(new java.awt.Color(204, 204, 204));
        plusButton22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton22.setText("0");
        plusButton22.setToolTipText("Add");
        plusButton22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton22ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegister.setText("Main Program");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        plusButton21.setBackground(new java.awt.Color(204, 204, 204));
        plusButton21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton21.setText("^");
        plusButton21.setToolTipText("Add");
        plusButton21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton21ActionPerformed(evt);
            }
        });

        plusButton23.setBackground(new java.awt.Color(204, 204, 204));
        plusButton23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton23.setText("√");
        plusButton23.setToolTipText("Add");
        plusButton23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton23ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        plusButton4.setBackground(new java.awt.Color(204, 204, 204));
        plusButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton4.setText("±");
        plusButton4.setToolTipText("Add");
        plusButton4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton4ActionPerformed(evt);
            }
        });

        plusButton1.setBackground(new java.awt.Color(204, 204, 204));
        plusButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton1.setText("<--");
        plusButton1.setToolTipText("Add");
        plusButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton1.setPreferredSize(new java.awt.Dimension(65, 30));
        plusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton1ActionPerformed(evt);
            }
        });

        plusButton25.setBackground(new java.awt.Color(204, 204, 204));
        plusButton25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton25.setText("π");
        plusButton25.setToolTipText("Add");
        plusButton25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton25.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton25ActionPerformed(evt);
            }
        });

        plusButton2.setBackground(new java.awt.Color(204, 204, 204));
        plusButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton2.setText("c");
        plusButton2.setToolTipText("Add");
        plusButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton2.setPreferredSize(new java.awt.Dimension(65, 30));
        plusButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton2ActionPerformed(evt);
            }
        });

        plusButton28.setBackground(new java.awt.Color(204, 204, 204));
        plusButton28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton28.setText("^2");
        plusButton28.setToolTipText("Add");
        plusButton28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton28.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton28ActionPerformed(evt);
            }
        });

        plusButton3.setBackground(new java.awt.Color(204, 204, 204));
        plusButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton3.setText("+");
        plusButton3.setToolTipText("Add");
        plusButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton3ActionPerformed(evt);
            }
        });

        plusButton31.setBackground(new java.awt.Color(204, 204, 204));
        plusButton31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton31.setText("^3");
        plusButton31.setToolTipText("Add");
        plusButton31.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton31.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton31ActionPerformed(evt);
            }
        });

        plusButton7.setBackground(new java.awt.Color(204, 204, 204));
        plusButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton7.setText("-");
        plusButton7.setToolTipText("Add");
        plusButton7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton7ActionPerformed(evt);
            }
        });

        plusButton34.setBackground(new java.awt.Color(204, 204, 204));
        plusButton34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton34.setText("log10");
        plusButton34.setToolTipText("Add");
        plusButton34.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton34.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton34ActionPerformed(evt);
            }
        });

        plusButton8.setBackground(new java.awt.Color(204, 204, 204));
        plusButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton8.setText("4");
        plusButton8.setToolTipText("Add");
        plusButton8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton8ActionPerformed(evt);
            }
        });

        plusButton37.setBackground(new java.awt.Color(204, 204, 204));
        plusButton37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plusButton37.setText("sin");
        plusButton37.setToolTipText("Add");
        plusButton37.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        plusButton37.setPreferredSize(new java.awt.Dimension(81, 30));
        plusButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButton37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(plusButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(plusButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(plusButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(plusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plusButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(plusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(plusButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plusButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plusButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plusButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(plusButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plusButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(plusButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plusButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plusButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(plusButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plusButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plusButton34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(plusButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plusButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(plusButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plusButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(plusButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(plusButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plusButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plusButton32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabelRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plusButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plusButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plusButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plusButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegister)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("About");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(350, 430);
    }//GEN-LAST:event_formWindowActivated

    private void plusButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton9ActionPerformed
        String inum = jTextField1.getText() + plusButton9.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton9ActionPerformed

    private void plusButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton38ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.cos(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton38ActionPerformed

    private void plusButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton10ActionPerformed
        String inum = jTextField1.getText() + plusButton10.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton10ActionPerformed

    private void plusButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton39ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.tan(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton39ActionPerformed

    private void plusButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton11ActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        operations = ("*");
        jLabel1.setText(firstnum + " *");
    }//GEN-LAST:event_plusButton11ActionPerformed

    private void plusButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton12ActionPerformed
        String inum = jTextField1.getText() + plusButton12.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton12ActionPerformed

    private void plusButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton40ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.log(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton40ActionPerformed

    private void plusButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton41ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.sinh(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton41ActionPerformed

    private void plusButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton13ActionPerformed
        String inum = jTextField1.getText() + plusButton13.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton13ActionPerformed

    private void plusButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton42ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.cosh(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton42ActionPerformed

    private void plusButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton14ActionPerformed
        String inum = jTextField1.getText() + plusButton14.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton14ActionPerformed

    private void plusButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton43ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.tanh(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton43ActionPerformed

    private void plusButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton15ActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        jLabel1.setText(firstnum + " /");
    }//GEN-LAST:event_plusButton15ActionPerformed

    private void plusButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton44ActionPerformed
        jTextField1.setText(String.valueOf(Math.E));
    }//GEN-LAST:event_plusButton44ActionPerformed

    private void plusButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton16ActionPerformed
        String inum = jTextField1.getText() + plusButton16.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton16ActionPerformed

    private void plusButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton26ActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        operations = ("%");
        jLabel1.setText(firstnum + " %");
    }//GEN-LAST:event_plusButton26ActionPerformed

    private void plusButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton17ActionPerformed
        String inum = jTextField1.getText() + plusButton17.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton17ActionPerformed

    private void plusButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton27ActionPerformed
        int a = Integer.parseInt(jTextField1.getText());
        jTextField1.setText(Integer.toString(a, 16));
    }//GEN-LAST:event_plusButton27ActionPerformed

    private void plusButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton18ActionPerformed
        String inum = jTextField1.getText() + plusButton18.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton18ActionPerformed

    private void plusButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton30ActionPerformed
        int a = Integer.parseInt(jTextField1.getText());
        jTextField1.setText(Integer.toString(a, 2));
    }//GEN-LAST:event_plusButton30ActionPerformed

    private void plusButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton19ActionPerformed
        String answer;
        secondnum = Double.parseDouble(jTextField1.getText());
        if ("+".equals(operations)) {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jTextField1.setText(answer);
        } else if ("-".equals(operations)) {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            jTextField1.setText(answer);
        } else if ("*".equals(operations)) {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            jTextField1.setText(answer);
        } else if ("/".equals(operations)) {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            jTextField1.setText(answer);
        } else if ("%".equals(operations)) {
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            jTextField1.setText(answer);
        } else if ("^".equals(operations)) {
            result = Math.pow(firstnum, secondnum);
            answer = String.format("%.2f", result);
            jTextField1.setText(answer);
        }
    }//GEN-LAST:event_plusButton19ActionPerformed

    private void plusButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton32ActionPerformed
        int a = Integer.parseInt(jTextField1.getText());
        jTextField1.setText(Integer.toString(a, 8));
    }//GEN-LAST:event_plusButton32ActionPerformed

    private void plusButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton20ActionPerformed
        if (!jTextField1.getText().contains(".")) {
            jTextField1.setText(jTextField1.getText() + plusButton20.getText());
        }
    }//GEN-LAST:event_plusButton20ActionPerformed

    private void plusButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton22ActionPerformed
        String inum = jTextField1.getText() + plusButton22.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton22ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        Home hf = new Home();
        hf.setVisible(true);
        hf.pack();
        hf.setLocationRelativeTo(null);
        hf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void plusButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton21ActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        operations = ("^");
        jLabel1.setText(firstnum + " ^");
    }//GEN-LAST:event_plusButton21ActionPerformed

    private void plusButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton23ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.sqrt(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton23ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void plusButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton4ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops *= (-1);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton4ActionPerformed

    private void plusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton1ActionPerformed
        int length = jTextField1.getText().length();
        int number = length - 1;
        String store = null;

        if (length > 0) {
            StringBuilder back = new StringBuilder(jTextField1.getText());
            back.deleteCharAt(number);
            store = back.toString();
            jTextField1.setText(store);
        }
    }//GEN-LAST:event_plusButton1ActionPerformed

    private void plusButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton25ActionPerformed
        jTextField1.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_plusButton25ActionPerformed

    private void plusButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton2ActionPerformed
        jTextField1.setText("");
        jLabel1.setText("");

    }//GEN-LAST:event_plusButton2ActionPerformed

    private void plusButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton28ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.pow(ops, 2);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton28ActionPerformed

    private void plusButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton3ActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        operations = ("+");
        jLabel1.setText(firstnum + " +");
    }//GEN-LAST:event_plusButton3ActionPerformed

    private void plusButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton31ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.pow(ops, 3);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton31ActionPerformed

    private void plusButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton7ActionPerformed
        firstnum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        operations = ("-");
        jLabel1.setText(firstnum + " -");
    }//GEN-LAST:event_plusButton7ActionPerformed

    private void plusButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton34ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.log10(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton34ActionPerformed

    private void plusButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton8ActionPerformed
        String inum = jTextField1.getText() + plusButton8.getText();
        jTextField1.setText(inum);
    }//GEN-LAST:event_plusButton8ActionPerformed

    private void plusButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButton37ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextField1.getText()));
        ops = Math.sin(ops);
        jTextField1.setText(String.valueOf(ops));
    }//GEN-LAST:event_plusButton37ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(null, "Calculator: Version 1.0\nProgrammer: Panagiotis Kourtzellis");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        JOptionPane.showMessageDialog(null, "Calculator: Version 1.0\nProgrammer: Panagiotis Kourtzellis");
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Home hf = new Home();
        hf.setVisible(true);
        hf.pack();
        hf.setLocationRelativeTo(null);
        hf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(620, 450);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(350, 450);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton plusButton1;
    private javax.swing.JButton plusButton10;
    private javax.swing.JButton plusButton11;
    private javax.swing.JButton plusButton12;
    private javax.swing.JButton plusButton13;
    private javax.swing.JButton plusButton14;
    private javax.swing.JButton plusButton15;
    private javax.swing.JButton plusButton16;
    private javax.swing.JButton plusButton17;
    private javax.swing.JButton plusButton18;
    private javax.swing.JButton plusButton19;
    private javax.swing.JButton plusButton2;
    private javax.swing.JButton plusButton20;
    private javax.swing.JButton plusButton21;
    private javax.swing.JButton plusButton22;
    private javax.swing.JButton plusButton23;
    private javax.swing.JButton plusButton25;
    private javax.swing.JButton plusButton26;
    private javax.swing.JButton plusButton27;
    private javax.swing.JButton plusButton28;
    private javax.swing.JButton plusButton3;
    private javax.swing.JButton plusButton30;
    private javax.swing.JButton plusButton31;
    private javax.swing.JButton plusButton32;
    private javax.swing.JButton plusButton34;
    private javax.swing.JButton plusButton37;
    private javax.swing.JButton plusButton38;
    private javax.swing.JButton plusButton39;
    private javax.swing.JButton plusButton4;
    private javax.swing.JButton plusButton40;
    private javax.swing.JButton plusButton41;
    private javax.swing.JButton plusButton42;
    private javax.swing.JButton plusButton43;
    private javax.swing.JButton plusButton44;
    private javax.swing.JButton plusButton7;
    private javax.swing.JButton plusButton8;
    private javax.swing.JButton plusButton9;
    // End of variables declaration//GEN-END:variables
}
